// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_std {
    use super::*;
    static FUNC: &str = "numpy_std";

    #[test]
    fn test_numeric() {
        // NumPy v2.5.2, _core/tests/test_numeric.py, TestNonarrayArgs::test_std (line 303)
        // NumPy uses assert_almost_equal (7 decimals); rstsr uses allclose.
        crate::specify_test!("test_numeric");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // A = [[1, 2, 3], [4, 5, 6]]
        // assert_almost_equal(np.std(A), 1.707825127659933)
        // assert_almost_equal(np.std(A, 0), np.array([1.5, 1.5, 1.5]))
        // assert_almost_equal(np.std(A, 1), np.array([0.81649658, 0.81649658]))
        // rstsr std requires a Float input (NumPy promotes int -> float); use f64.
        let a: Tensor<f64, _> = rt::tensor_from_nested!([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], &device);

        let out_all = a.std_axes(None);
        let expected_all: Tensor<f64, _> = rt::asarray((1.707825127659933, &device));
        assert_equal(&out_all, &expected_all, None);

        assert_equal(&a.std_axes(0), &rt::tensor_from_nested!([1.5, 1.5, 1.5], &device), None);

        // exact sqrt(2/3) = 0.8164965809277260; NumPy rounds to 0.81649658.
        assert_equal(&a.std_axes(1), &rt::tensor_from_nested!([0.816496580927726, 0.816496580927726], &device), None);
    }
}
