// Most or all contents generated by AI (agent session 2026-10-05).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod custom_reduction_dtype {
    use super::*;
    static FUNC: &str = "custom_reduction_dtype";

    #[test]
    fn test_sum_with_dtype_widening() {
        crate::specify_test!("test_sum_with_dtype_widening");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.sum(np.array([1, 2, 3], dtype=np.int32), dtype=np.int64) -> 6 (int64)
        let a: Tensor<i32, _> = rt::tensor_from_nested!([1, 2, 3], &device);
        let s: Tensor<i64, _> = rt::sum_with_dtype(&a, ());
        assert_eq!(s.shape(), &[] as &[usize]);
        assert_eq!(s.to_scalar(), 6i64);

        // axes + keepdims: [[1, 2], [3, 4]] -> [[4, 6]]
        let b: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let s: Tensor<i64, _> = b.sum_with_dtype((0, true));
        assert_eq!(s.shape(), &[1, 2]);
        assert_eq!(s.raw(), &[4i64, 6]);

        // float accumulation of an integer tensor
        // np.sum(np.array([[1, 2], [3, 4]]), axis=1, dtype=np.float64) -> [3.0, 7.0]
        let s: Tensor<f64, _> = b.sum_with_dtype(1);
        assert_eq!(s.raw(), &[3.0f64, 7.0]);
    }

    #[test]
    fn test_sum_with_dtype_overflow_prevention() {
        crate::specify_test!("test_sum_with_dtype_overflow_prevention");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.array([10, 20, 30, 40], dtype=np.int8).sum(dtype=np.int64) -> 100
        // (accumulating in int8 instead would overflow)
        let a: Tensor<i8, _> = rt::tensor_from_nested!([10, 20, 30, 40], &device);
        let s: Tensor<i64, _> = rt::sum_with_dtype(&a, ());
        assert_eq!(s.to_scalar(), 100i64);
    }

    #[test]
    fn test_prod_mean_with_dtype() {
        crate::specify_test!("test_prod_mean_with_dtype");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.prod(np.array([1, 2, 3, 4], dtype=np.int8), dtype=np.int64) -> 24
        let a: Tensor<i8, _> = rt::tensor_from_nested!([1, 2, 3, 4], &device);
        let p: Tensor<i64, _> = rt::prod_with_dtype(&a, ());
        assert_eq!(p.to_scalar(), 24i64);

        // np.mean(np.array([[1, 2], [3, 4]], dtype=np.int32), axis=0, dtype=np.float64)
        //   -> [2.0, 3.0]
        // (rstsr `mean` itself requires float input; the `_with_dtype` form casts first)
        let b: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let m: Tensor<f64, _> = b.mean_with_dtype(0);
        assert_eq!(m.raw(), &[2.0f64, 3.0]);

        // np.mean(np.array([1.0, 2.0], dtype=np.float64), dtype=np.float32) -> 1.5 (float32)
        let c: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0], &device);
        let m: Tensor<f32, _> = c.mean_with_dtype(());
        assert_eq!(m.to_scalar(), 1.5f32);
    }

    #[test]
    fn test_var_std_with_dtype() {
        crate::specify_test!("test_var_std_with_dtype");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
        // np.var(a, axis=1, dtype=np.float64) -> [0.66666667, 0.66666667]
        let a: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let v: Tensor<f64, _> = a.var_with_dtype(1);
        assert_equal(&v, &rt::tensor_from_nested!([2.0 / 3.0, 2.0 / 3.0], &device), None);

        // np.std(a, axis=1, dtype=np.float64) -> [0.81649658, 0.81649658]
        let s: Tensor<f64, _> = a.std_with_dtype(1);
        assert_equal(&s, &rt::tensor_from_nested!([0.816496580927726, 0.816496580927726], &device), None);

        // correction (Delta degrees of freedom) combined with an explicit dtype
        // np.var(a, axis=1, ddof=1, dtype=np.float64) -> [1.0, 1.0]
        let v: Tensor<f64, _> = a.var_with_dtype(VarArgs::default().axes(1).correction(1.0));
        assert_equal(&v, &rt::tensor_from_nested!([1.0, 1.0], &device), None);

        // float32 accumulation of a float64 tensor
        let b: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0, 3.0], &device);
        let v: Tensor<f32, _> = b.var_with_dtype(());
        assert_eq!(v.to_scalar(), 2.0f32 / 3.0);
    }

    #[test]
    fn test_var_with_dtype_nan_dof() {
        crate::specify_test!("test_var_with_dtype_nan_dof");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // M - correction <= 0 -> NaN (Array-API: `correction` >= M yields NaN)
        let a: Tensor<f64, _> = rt::tensor_from_nested!([3.0], &device);
        let v: Tensor<f64, _> = a.var_with_dtype(VarArgs::default().correction(1.0));
        assert!(v.to_scalar().is_nan());

        // same through the non-dtype entry
        let v = a.var_with_args(VarArgs::default().correction(1.0));
        assert!(v.to_scalar().is_nan());
    }

    #[test]
    fn test_sum_with_dtype_complex_target() {
        crate::specify_test!("test_sum_with_dtype_complex_target");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // real -> complex cast is available; the sum accumulates in complex64
        let a: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0], &device);
        let s: Tensor<num::Complex<f64>, _> = rt::sum_with_dtype(&a, ());
        assert_eq!(s.to_scalar(), num::Complex::new(3.0, 0.0));
    }
}
