// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_prod {
    use super::*;
    static FUNC: &str = "numpy_prod";

    #[test]
    fn test_numeric() {
        // NumPy v2.5.2, _core/tests/test_numeric.py, TestNonarrayArgs::test_prod (line 157)
        crate::specify_test!("test_numeric");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // arr = [[1, 2, 3, 4], [5, 6, 7, 9], [10, 3, 4, 5]]
        // tgt = [24, 1890, 600]
        // assert_equal(np.prod(arr, axis=-1), tgt)
        let arr = rt::tensor_from_nested!([[1, 2, 3, 4], [5, 6, 7, 9], [10, 3, 4, 5]], &device);
        let out = arr.prod_axes(-1);
        let expected = rt::tensor_from_nested!([24, 1890, 600], &device);
        assert_equal(&out, &expected, None);
    }

    #[test]
    fn test_basic() {
        // NumPy v2.5.2, lib/tests/test_function_base.py, TestProd::test_basic (line 770)
        // NumPy iterates many dtypes; rstsr transfers the i32 value cases only.
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // ba = [1, 2, 10, 11, 6, 5, 4]  -> a.prod(axis=0) == 26400
        // ba2 = [[1, 2, 3, 4], [5, 6, 7, 9], [10, 3, 4, 5]]
        //   a2.prod(axis=0) == [50, 36, 84, 180]
        //   a2.prod(axis=-1) == [24, 1890, 600]
        let a = rt::tensor_from_nested!([1, 2, 10, 11, 6, 5, 4], &device);
        assert_eq!(a.prod_all(), 26400);

        let a2 = rt::tensor_from_nested!([[1, 2, 3, 4], [5, 6, 7, 9], [10, 3, 4, 5]], &device);
        assert_equal(a2.prod_axes(0), rt::tensor_from_nested!([50, 36, 84, 180], &device), None);
        assert_equal(a2.prod_axes(-1), rt::tensor_from_nested!([24, 1890, 600], &device), None);
    }
}

#[cfg(test)]
mod custom_prod {
    use super::*;
    static FUNC: &str = "custom_prod";

    #[test]
    fn test_prod_axis_none() {
        crate::specify_test!("test_prod_axis_none");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // prod_axes(None) reduces over all axes -> 0-d tensor.
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let out = a.prod_axes(None);
        assert_eq!(out.to_scalar(), 720);
    }
}
