// Most or all contents generated by AI (agent session 2026-10-05).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod custom_reduction_args {
    use super::*;
    static FUNC: &str = "custom_reduction_args";

    #[test]
    fn test_sum_with_args_keepdims() {
        crate::specify_test!("test_sum_with_args_keepdims");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[1, 2], [3, 4]])
        // np.sum(a, axis=0, keepdims=True) -> [[4, 6]]
        // np.sum(a, axis=1, keepdims=True) -> [[3], [7]]
        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let s = rt::sum_with_args(&a, (0, true));
        assert_eq!(s.shape(), &[1, 2]);
        assert_equal(&s, &rt::tensor_from_nested!([[4, 6]], &device), None);

        let s = a.sum_with_args((1, true));
        assert_eq!(s.shape(), &[2, 1]);
        assert_equal(&s, &rt::tensor_from_nested!([[3], [7]], &device), None);

        // np.sum(a, keepdims=True) -> [[10]]
        let s = a.sum_with_args(true);
        assert_eq!(s.shape(), &[1, 1]);
        assert_equal(&s, &rt::tensor_from_nested!([[10]], &device), None);

        // np.sum(a, axis=(0, 1), keepdims=True) -> [[10]]
        let s = a.sum_with_args(([0, 1], true));
        assert_eq!(s.shape(), &[1, 1]);
        assert_equal(&s, &rt::tensor_from_nested!([[10]], &device), None);

        // negative axes
        let s = a.sum_with_args((-1, true));
        assert_equal(&s, &rt::tensor_from_nested!([[3], [7]], &device), None);
    }

    #[test]
    fn test_sum_with_args_no_keepdims() {
        crate::specify_test!("test_sum_with_args_no_keepdims");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);

        // np.sum(a, axis=1)
        let s = a.sum_with_args(1);
        assert_eq!(s.shape(), &[2]);
        assert_equal(&s, &rt::tensor_from_nested!([3, 7], &device), None);

        // whole reduce without keepdims -> 0-d tensor
        let s = a.sum_with_args(ReduceArgs::default());
        assert_eq!(s.shape(), &[] as &[usize]);
        assert_eq!(s.to_scalar(), 10);

        // whole reduce with keepdims -> all size-1 shape
        let s = a.sum_with_args(true);
        assert_eq!(s.to_scalar(), 10);
    }

    #[test]
    fn test_reduction_args_other_families() {
        crate::specify_test!("test_reduction_args_other_families");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[3, 1, 2], [6, 4, 5]], &device);

        // np.min(a, axis=1, keepdims=True) -> [[1], [4]]
        let m = a.min_with_args((1, true));
        assert_equal(&m, &rt::tensor_from_nested!([[1], [4]], &device), None);

        // np.max(a, axis=0, keepdims=True) -> [[6, 4, 5]]
        let m = a.max_with_args((0, true));
        assert_equal(&m, &rt::tensor_from_nested!([[6, 4, 5]], &device), None);

        // np.prod(a, axis=1, keepdims=True) -> [[6], [120]]
        let m = a.prod_with_args((1, true));
        assert_equal(&m, &rt::tensor_from_nested!([[6], [120]], &device), None);

        // np.count_nonzero(a, axis=1, keepdims=True) -> [[3], [3]]
        let m = a.count_nonzero_with_args((1, true));
        assert_equal(&m, &rt::tensor_from_nested!([[3], [3]], &device), None);

        // np.argmax(a, axis=1, keepdims=True) -> [[0], [0]]
        let m = a.argmax_with_args((1, true));
        assert_eq!(m.shape(), &[2, 1]);
        assert_equal(&m, &rt::tensor_from_nested!([[0], [0]], &device), None);

        let b = rt::tensor_from_nested!([[true, false], [true, true]], &device);

        // np.all(b, axis=1, keepdims=True) -> [[False], [True]]
        let m = b.all_with_args((1, true));
        assert_eq!(m.shape(), &[2, 1]);
        assert_eq!(m.raw(), &[false, true]);

        // np.any(b, axis=0, keepdims=True) -> [[True, True]]
        let m = b.any_with_args((0, true));
        assert_eq!(m.shape(), &[1, 2]);
        assert_eq!(m.raw(), &[true, true]);

        // bool sum: np.sum(b, axis=0, keepdims=True) -> [[2, 1]]
        let m = b.sum_with_args((0, true));
        assert_eq!(m.shape(), &[1, 2]);
        assert_eq!(m.raw(), &[2, 1]);
    }

    #[test]
    fn test_var_std_with_args_correction() {
        crate::specify_test!("test_var_std_with_args_correction");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        // np.var(a, axis=1)  -> [0.66666667, 0.66666667]
        // np.var(a, axis=1, ddof=1) -> [1., 1.]
        let a = rt::tensor_from_nested!([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], &device);

        let v = a.var_with_args(1);
        assert_equal(&v, &rt::tensor_from_nested!([2.0 / 3.0, 2.0 / 3.0], &device), None);

        let v = a.var_with_args(VarArgs::default().axes(1).keepdims(true).correction(1.0));
        assert_equal(&v, &rt::tensor_from_nested!([[1.0], [1.0]], &device), None);
    }
}
