// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_var {
    use super::*;
    static FUNC: &str = "numpy_var";

    #[test]
    fn test_numeric() {
        // NumPy v2.5.2, _core/tests/test_numeric.py, TestNonarrayArgs::test_var (line 360)
        // NumPy uses assert_almost_equal (7 decimals); rstsr uses allclose.
        crate::specify_test!("test_numeric");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // A = [[1, 2, 3], [4, 5, 6]]
        // assert_almost_equal(np.var(A), 2.9166666666666665)
        // assert_almost_equal(np.var(A, 0), np.array([2.25, 2.25, 2.25]))
        // assert_almost_equal(np.var(A, 1), np.array([0.66666667, 0.66666667]))
        // rstsr var requires a Float input (NumPy promotes int -> float); use f64.
        let a: Tensor<f64, _> = rt::tensor_from_nested!([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], &device);

        let out_all = a.var_axes(None);
        let expected_all: Tensor<f64, _> = rt::asarray((2.9166666666666665, &device));
        assert_equal(&out_all, &expected_all, None);

        assert_equal(a.var_axes(0), rt::tensor_from_nested!([2.25, 2.25, 2.25], &device), None);

        // exact 2/3 = 0.6666666666666666; NumPy rounds to 0.66666667.
        assert_equal(a.var_axes(1), rt::tensor_from_nested!([0.6666666666666666, 0.6666666666666666], &device), None);
    }
}
