// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_any {
    use super::*;
    static FUNC: &str = "numpy_any";

    #[test]
    fn test_basic() {
        // NumPy v2.5.2, lib/tests/test_function_base.py, TestAny::test_basic (line 266)
        // NumPy uses int 0/1 as truthy; rstsr uses bool tensors (semantically identical).
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // y1 = [0, 0, 1, 0]; y2 = [0, 0, 0, 0]; y3 = [1, 0, 1, 0]
        // assert_(np.any(y1))
        // assert_(np.any(y3))
        // assert_(not np.any(y2))
        let y1 = rt::tensor_from_nested!([false, false, true, false], &device);
        let y2 = rt::tensor_from_nested!([false, false, false, false], &device);
        let y3 = rt::tensor_from_nested!([true, false, true, false], &device);
        assert!(y1.any_all());
        assert!(y3.any_all());
        assert!(!y2.any_all());
    }

    #[test]
    fn test_nd() {
        // NumPy v2.5.2, lib/tests/test_function_base.py, TestAny::test_nd (line 274)
        crate::specify_test!("test_nd");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // y1 = [[0, 0, 0], [0, 1, 0], [1, 1, 0]]
        // assert_(np.any(y1))
        // assert_array_equal(np.any(y1, axis=0), [1, 1, 0])
        // assert_array_equal(np.any(y1, axis=1), [0, 1, 1])
        let y1 = rt::tensor_from_nested!([[false, false, false], [false, true, false], [true, true, false]], &device);
        assert!(y1.any_all());
        // bool result tensors can't use assert_equal (bool: ExtNum unsatisfied);
        // compare via to_vec() instead.
        assert_eq!(y1.any_axes(0).to_vec(), vec![true, true, false]);
        assert_eq!(y1.any_axes(1).to_vec(), vec![false, true, true]);
    }
}
