// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_argmax {
    use super::*;
    static FUNC: &str = "numpy_argmax";

    #[test]
    fn test_combinations() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, TestArgmax::test_combinations (line 5538)
        // NumPy parametrizes a large dtype/nan/datetime table; rstsr transfers the 4
        // value cases (usg_data, defined L5441) as i32. Reversed-array rows not ported.
        crate::specify_test!("test_combinations");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // CASE usg_data L5441: [1,1,1,1,1,1,1,1,0,0,0,0,0,0,0] -> argmax 0
        let a = rt::tensor_from_nested!([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], &device);
        assert_eq!(a.argmax_all(), 0);

        // CASE usg_data L5442: [3,3,3,3,2,2,2,2] -> argmax 0
        let a = rt::tensor_from_nested!([3, 3, 3, 3, 2, 2, 2, 2], &device);
        assert_eq!(a.argmax_all(), 0);

        // CASE usg_data L5443: [0,1,2,3,4,5,6,7] -> argmax 7
        let a = rt::tensor_from_nested!([0, 1, 2, 3, 4, 5, 6, 7], &device);
        assert_eq!(a.argmax_all(), 7);

        // CASE usg_data L5444: [7,6,5,4,3,2,1,0] -> argmax 0
        let a = rt::tensor_from_nested!([7, 6, 5, 4, 3, 2, 1, 0], &device);
        assert_eq!(a.argmax_all(), 0);
    }

    #[test]
    fn test_regression() {
        // NumPy v2.5.2, _core/tests/test_regression.py, TestRegression::test_argmax (line 262)
        // Ticket #119: high-dimensional argmax along each axis should succeed.
        crate::specify_test!("test_regression");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.random.normal(0, 1, (4, 5, 6, 7, 8))
        // for i in range(a.ndim):
        //     a.argmax(i)  # Should succeed
        let a = rt::arange((4 * 5 * 6 * 7 * 8, &device)).into_shape([4, 5, 6, 7, 8]);
        for i in 0..a.ndim() {
            let _ = a.argmax_axes(i as isize); // Should succeed
        }
    }
}

#[cfg(test)]
mod custom_argmax {
    use super::*;
    static FUNC: &str = "custom_argmax";

    #[test]
    fn test_argmax_axes_2d() {
        crate::specify_test!("test_argmax_axes_2d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // b = [[3, 6, 9], [4, 10, 5], [8, 3, 2]]
        // np.argmax(b, axis=0) == [2, 1, 0]  (col max indices)
        // np.argmax(b, axis=1) == [2, 1, 0]  (row max indices)
        let b = rt::tensor_from_nested!([[3, 6, 9], [4, 10, 5], [8, 3, 2]], &device);

        assert_eq!(b.argmax_axes(0).to_vec(), vec![2, 1, 0]);
        assert_eq!(b.argmax_axes(1).to_vec(), vec![2, 1, 0]);
    }
}
