// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_argmin {
    use super::*;
    static FUNC: &str = "numpy_argmin";

    #[test]
    fn test_combinations() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, TestArgmin::test_combinations (line 5682)
        // NumPy parametrizes a large dtype/nan/datetime table; rstsr transfers the 4
        // value cases (usg_data, defined L5585) as i32. Reversed-array rows not ported.
        crate::specify_test!("test_combinations");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // CASE usg_data L5585: [1,1,1,1,1,1,1,1,0,0,0,0,0,0,0] -> argmin 8
        let a = rt::tensor_from_nested!([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], &device);
        assert_eq!(a.argmin_all(), 8);

        // CASE usg_data L5586: [3,3,3,3,2,2,2,2] -> argmin 4
        let a = rt::tensor_from_nested!([3, 3, 3, 3, 2, 2, 2, 2], &device);
        assert_eq!(a.argmin_all(), 4);

        // CASE usg_data L5587: [0,1,2,3,4,5,6,7] -> argmin 0
        let a = rt::tensor_from_nested!([0, 1, 2, 3, 4, 5, 6, 7], &device);
        assert_eq!(a.argmin_all(), 0);

        // CASE usg_data L5588: [7,6,5,4,3,2,1,0] -> argmin 7
        let a = rt::tensor_from_nested!([7, 6, 5, 4, 3, 2, 1, 0], &device);
        assert_eq!(a.argmin_all(), 7);
    }
}

#[cfg(test)]
mod custom_argmin {
    use super::*;
    static FUNC: &str = "custom_argmin";

    #[test]
    fn test_argmin_axes_2d() {
        crate::specify_test!("test_argmin_axes_2d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // b = [[3, 6, 9], [4, 10, 5], [8, 3, 2]]
        // np.argmin(b, axis=1) == [0, 0, 2]  (row min indices)
        let b = rt::tensor_from_nested!([[3, 6, 9], [4, 10, 5], [8, 3, 2]], &device);

        assert_eq!(b.argmin_axes(1).to_vec(), vec![0, 0, 2]);
    }
}
