// Soundness guard for allocatable (non-POD) dtypes on the SAFE public API surface.
//
// Most or all contents generated by AI (model glm-5.3-flash)

use num_bigint::BigInt;
use rstsr::prelude::*;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;

/// Parse a decimal string into a `BigInt` (test helper; panics on bad input).
fn big(s: &str) -> BigInt {
    BigInt::parse_bytes(s.as_bytes(), 10).unwrap()
}

/// Plain-Rust reference matmul on nested row-major values (exact BigInt arithmetic).
fn matmul_ref(a: &[Vec<BigInt>], b: &[Vec<BigInt>]) -> Vec<Vec<BigInt>> {
    let (m, k, n) = (a.len(), b.len(), b[0].len());
    (0..m).map(|i| (0..n).map(|j| (0..k).fold(BigInt::from(0), |acc, p| acc + &a[i][p] * &b[p][j])).collect()).collect()
}

fn nested(flat: &[BigInt], rows: usize, cols: usize) -> Vec<Vec<BigInt>> {
    (0..rows).map(|i| (0..cols).map(|j| flat[i * cols + j].clone()).collect()).collect()
}

fn flatten(nested: &[Vec<BigInt>]) -> Vec<BigInt> {
    nested.iter().flatten().cloned().collect()
}

#[test]
fn test_creation_asarray_from_vec_and_nested() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    // `rt::asarray((vec, shape, &device))` moves the `Vec` into the storage
    // (`outof_cpu_vec`): no copy, no re-initialization.
    let data = vec![
        big("10000000000000000000000000"), // 10^25, far beyond u64/i64 range
        big("-3"),
        big("7"),
        big("9"),
        big("11"),
        big("-13"),
    ];
    let a = rt::asarray((data, [2, 3], &device));
    assert_eq!(a.shape(), &[2, 3]);
    assert_eq!(
        a.into_shape(-1).into_vec(),
        vec![big("10000000000000000000000000"), big("-3"), big("7"), big("9"), big("11"), big("-13"),]
    );

    // `tensor_from_nested!` (bounds: `T: Clone` + `DeviceCreationAnyAPI`).
    let b = rt::tensor_from_nested!([[big("10"), big("-20")], [big("30"), big("-40")]], &device);
    assert_eq!(b.shape(), &[2, 2]);
    assert_eq!(b.into_shape(-1).into_vec(), vec![big("10"), big("-20"), big("30"), big("-40")]);
}

#[test]
fn test_creation_zeros_ones_full_arange() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    // zeros/ones go through `DeviceCreationNumAPI` (`T: Num`): every element is
    // constructed from `T::zero()`/`T::one()`, never read from raw memory.
    let z: Tensor<BigInt, _, _> = rt::zeros(([2, 3], &device));
    assert_eq!(z.into_shape(-1).into_vec(), vec![BigInt::from(0); 6]);

    let o: Tensor<BigInt, _, _> = rt::ones(([2, 3], &device));
    assert_eq!(o.into_shape(-1).into_vec(), vec![BigInt::from(1); 6]);

    // `full` only requires `T: Clone`.
    let f: Tensor<BigInt, _, _> = rt::full(([2, 3], big("999999999999999999999999999"), &device));
    assert_eq!(f.into_shape(-1).into_vec(), vec![big("999999999999999999999999999"); 6]);

    // `arange` requires `Zero + One + PartialOrd + Add + Clone + 'static`.
    let r = rt::arange((BigInt::from(2), BigInt::from(14), BigInt::from(3), &device));
    assert_eq!(r.into_shape(-1).into_vec(), vec![BigInt::from(2), BigInt::from(5), BigInt::from(8), BigInt::from(11)]);
}

#[test]
fn test_elementwise_add_sub_mul_neg() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    let a = rt::asarray((
        vec![
            big("1000000000000000000000000"), // 10^24
            big("-20"),
            big("30"),
            big("4"),
            big("5"),
            big("-6"),
        ],
        [2, 3],
        &device,
    ));
    let b = rt::asarray((
        vec![big("7"), big("2"), big("-3"), big("1000000000000000000000000"), big("1"), big("6")],
        [2, 3],
        &device,
    ));

    // element-wise add: exact, mixed magnitudes
    let s = rt::add(&a, &b);
    assert_eq!(s.shape(), &[2, 3]);
    assert_eq!(
        s.into_shape(-1).into_vec(),
        vec![
            big("1000000000000000000000007"),
            big("-18"),
            big("27"),
            big("1000000000000000000000004"),
            big("6"),
            big("0"),
        ]
    );

    // element-wise sub
    let d = rt::sub(&a, &b);
    assert_eq!(
        d.into_shape(-1).into_vec(),
        vec![
            big("999999999999999999999993"),
            big("-22"),
            big("33"),
            big("-999999999999999999999996"),
            big("4"),
            big("-12"),
        ]
    );

    // element-wise mul: products of ~10^24-scale values stay exact
    let m = rt::mul(&a, &b);
    assert_eq!(
        m.into_shape(-1).into_vec(),
        vec![
            big("7000000000000000000000000"),
            big("-40"),
            big("-90"),
            big("4000000000000000000000000"),
            big("5"),
            big("-36"),
        ]
    );

    // unary neg
    let n = rt::neg(&a);
    assert_eq!(
        n.into_shape(-1).into_vec(),
        vec![big("-1000000000000000000000000"), big("20"), big("-30"), big("-4"), big("-5"), big("6"),]
    );

    // broadcast: row `[3]` against the last axis of `[2, 3]`
    let row = rt::asarray((vec![big("1000000000000000000000000"), big("-2000"), big("3000")], &device));
    let c = rt::add(&a, &row);
    assert_eq!(c.shape(), &[2, 3]);
    assert_eq!(
        c.into_shape(-1).into_vec(),
        vec![
            big("2000000000000000000000000"),
            big("-2020"),
            big("3030"),
            big("1000000000000000000000004"),
            big("-1995"),
            big("2994"),
        ]
    );
}

#[test]
fn test_strided_copy_to_contig() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    let a = rt::asarray((vec![big("10"), big("-20"), big("30"), big("40"), big("-50"), big("60")], [2, 3], &device));
    // transpose is a layout-only view; `to_contig` materializes a new storage by
    // element-wise copy (strided read -> fresh contiguous write)
    let at = a.swapaxes(0, 1);
    assert_eq!(at.shape(), &[3, 2]);
    let contig = at.to_contig(RowMajor);
    assert_eq!(contig.shape(), &[3, 2]);
    assert_eq!(
        contig.into_shape(-1).into_vec(),
        vec![big("10"), big("40"), big("-20"), big("-50"), big("30"), big("60")]
    );
}

#[test]
fn test_matmul_with_output_initialized_buffer() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    // 2x3 @ 3x2 with one huge-scale entry; exact BigInt values
    let a = rt::asarray((
        vec![
            big("10000000000000000000000000"), // 10^25
            big("2"),
            big("3"),
            big("4"),
            big("5"),
            big("6"),
        ],
        [2, 3],
        &device,
    ));
    let b = rt::asarray((vec![big("7"), big("8"), big("9"), big("10"), big("11"), big("12")], [3, 2], &device));

    // This variant writes into a fully initialized (`zeros`) output buffer;
    // the allocating form (`rt::matmul`) is covered by
    // `test_matmul_allocating_exact` below.
    let mut c: Tensor<BigInt, _> = rt::zeros(([2, 2], &device));
    rt::matmul_with_output(&a, &b, &mut c);
    assert_eq!(
        c.into_shape(-1).into_vec(),
        vec![
            big("70000000000000000000000051"), // 7 * 10^25 + 2*9 + 3*11
            big("80000000000000000000000056"), // 8 * 10^25 + 2*10 + 3*12
            big("139"),                        // 4*7 + 5*9 + 6*11
            big("154"),                        // 4*8 + 5*10 + 6*12
        ]
    );

    // non-contiguous operands: (3, 2) = a^T, (2, 3) = b^T
    let a_flat = vec![big("10000000000000000000000000"), big("2"), big("3"), big("4"), big("5"), big("6")];
    let b_flat = vec![big("7"), big("8"), big("9"), big("10"), big("11"), big("12")];
    let at_ref = nested(&a_flat, 2, 3);
    let bt_ref = nested(&b_flat, 3, 2);
    let expected = flatten(&matmul_ref(&transpose(&at_ref), &transpose(&bt_ref)));

    let at = a.swapaxes(0, 1);
    let bt = b.swapaxes(0, 1);
    let mut d: Tensor<BigInt, _> = rt::zeros(([3, 3], &device));
    rt::matmul_with_output(&at, &bt, &mut d);
    assert_eq!(d.into_shape(-1).into_vec(), expected);
}

fn transpose(v: &[Vec<BigInt>]) -> Vec<Vec<BigInt>> {
    let (rows, cols) = (v.len(), v[0].len());
    (0..cols).map(|j| (0..rows).map(|i| v[i][j].clone()).collect()).collect()
}

/// Regression: the *allocating* `rt::matmul` must be sound for allocatable
/// dtypes. It used to allocate with `unsafe { empty }` and the kernel read each
/// output element before writing it (`beta * c[idx]` at `beta = 0`) — for
/// BigInt that read uninitialized memory and dropped garbage (see file header).
/// Fixed by the write-only fresh-output path (`matmul_uninit` on `MaybeUninit`
/// storage); guarded here by exact values.
#[test]
fn test_matmul_allocating_exact() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    let a = rt::asarray((
        vec![big("10000000000000000000000000"), big("2"), big("3"), big("4"), big("5"), big("6")],
        [2, 3],
        &device,
    ));
    let b = rt::asarray((vec![big("7"), big("8"), big("9"), big("10"), big("11"), big("12")], [3, 2], &device));

    // function form (allocating output)
    let c = rt::matmul(&a, &b);
    assert_eq!(c.shape(), &[2, 2]);
    assert_eq!(
        c.into_shape(-1).into_vec(),
        vec![
            big("70000000000000000000000051"), // 7 * 10^25 + 2*9 + 3*11
            big("80000000000000000000000056"), // 8 * 10^25 + 2*10 + 3*12
            big("139"),                        // 4*7 + 5*9 + 6*11
            big("154"),                        // 4*8 + 5*10 + 6*12
        ]
    );

    // method form, with a reference cross-check
    let d = a.matmul(&b);
    let a_ref = nested(&[big("10000000000000000000000000"), big("2"), big("3"), big("4"), big("5"), big("6")], 2, 3);
    let b_ref = nested(&[big("7"), big("8"), big("9"), big("10"), big("11"), big("12")], 3, 2);
    assert_eq!(d.into_shape(-1).into_vec(), flatten(&matmul_ref(&a_ref, &b_ref)));

    // batched case: (2, 1, 2) @ (2, 2) -> (2, 1, 2); the naive kernel routes
    // this through the batched branch, not the 2-D fast path
    let e = rt::asarray((vec![big("1"), big("2"), big("3"), big("4")], [2, 1, 2], &device));
    let f = rt::asarray((vec![big("5"), big("6"), big("7"), big("8")], [2, 2], &device));
    let g = rt::matmul(&e, &f);
    assert_eq!(g.shape(), &[2, 1, 2]);
    assert_eq!(
        g.into_shape(-1).into_vec(),
        vec![
            big("19"),
            big("22"), // [1, 2] @ [[5, 6], [7, 8]]
            big("43"),
            big("50"), // [3, 4] @ [[5, 6], [7, 8]]
        ]
    );
}

#[test]
fn test_reduction_sum_exact() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    let a = rt::asarray((
        vec![
            big("10000000000000000000000000"), // 10^25
            big("-3"),
            big("7"),
            big("9"),
            big("11"),
            big("-13"),
        ],
        [2, 3],
        &device,
    ));

    // whole-tensor reduction: `T: Zero + Add + Clone` on the device side
    let total = rt::sum(&a);
    assert_eq!(total, big("10000000000000000000000011"));

    // axis reductions
    let s0 = rt::sum_axes(&a, 0);
    assert_eq!(s0.shape(), &[3]);
    assert_eq!(s0.into_shape(-1).into_vec(), vec![big("10000000000000000000000009"), big("8"), big("-6")]);

    let s1 = rt::sum_axes(&a, 1);
    assert_eq!(s1.into_shape(-1).into_vec(), vec![big("10000000000000000000000004"), big("7")]);
}

/* #region Drop guard: every element dropped exactly once */

#[derive(Default)]
struct GuardCounters {
    created: AtomicUsize,
    dropped: AtomicUsize,
}

/// A heap-allocating, non-Copy dtype with a `Drop` impl. Every genuine
/// construction (including every `clone`) increments `created`; every drop
/// increments `dropped`. If any kernel reads uninitialized memory interpreted
/// as this type (and drops it), or double-drops, or leaks elements, the
/// `created == dropped` invariant in the test below fails (or the process
/// crashes outright).
struct DropGuard {
    payload: Vec<u8>,
    counters: Arc<GuardCounters>,
}

impl DropGuard {
    fn new(counters: Arc<GuardCounters>) -> Self {
        counters.created.fetch_add(1, Ordering::SeqCst);
        DropGuard { payload: vec![0xA5; 256], counters }
    }
}

impl Clone for DropGuard {
    fn clone(&self) -> Self {
        self.counters.created.fetch_add(1, Ordering::SeqCst);
        DropGuard { payload: self.payload.clone(), counters: self.counters.clone() }
    }
}

impl Drop for DropGuard {
    fn drop(&mut self) {
        self.counters.dropped.fetch_add(1, Ordering::SeqCst);
    }
}

impl std::ops::Add for DropGuard {
    type Output = DropGuard;
    fn add(self, rhs: DropGuard) -> DropGuard {
        let counters = self.counters.clone();
        drop((self, rhs)); // both operands drop exactly once, as real values would
        DropGuard::new(counters)
    }
}

impl std::ops::Mul for DropGuard {
    type Output = DropGuard;
    fn mul(self, rhs: DropGuard) -> DropGuard {
        let counters = self.counters.clone();
        drop((self, rhs));
        DropGuard::new(counters)
    }
}

#[test]
fn test_drop_guard_created_equals_dropped() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);
    let counters = Arc::new(GuardCounters::default());
    {
        let vec: Vec<DropGuard> = (0..6).map(|_| DropGuard::new(counters.clone())).collect();
        let a = rt::asarray((vec, [2, 3], &device));
        // element-wise ops clone every operand element and construct every
        // output element; to_contig copies every element once more
        let b = rt::add(&a, &a);
        let c = rt::mul(&a, &b);
        let at = a.swapaxes(0, 1);
        let contig = at.to_contig(RowMajor);
        assert_eq!(b.shape(), &[2, 3]);
        assert_eq!(c.shape(), &[2, 3]);
        assert_eq!(contig.shape(), &[3, 2]);
        // all tensors (and every element inside them) drop here
    }
    let created = counters.created.load(Ordering::SeqCst);
    let dropped = counters.dropped.load(Ordering::SeqCst);
    assert!(created > 6, "ops must have cloned/copied elements (created = {created})");
    assert_eq!(
        created, dropped,
        "every DropGuard must be dropped exactly once (no leak, no double drop, no drop of uninitialized memory)"
    );
}

/* #endregion */

/* #region diag/concatenate: migrated from `empty` + `assign` to `uninit` + `assign_uninit` */

#[test]
fn test_diag_concat_allocatable_exact() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);

    // diag extraction: 2-D -> 1-D (the migrated uninit + assign_uninit path)
    let a = rt::asarray((vec![big("10000000000000000000000000"), big("2"), big("3"), big("4")], [2, 2], &device));
    let d0 = rt::diag((&a, 0));
    assert_eq!(d0.shape(), &[2]);
    assert_eq!(d0.into_shape(-1).into_vec(), vec![big("10000000000000000000000000"), big("4")]);
    let d1 = rt::diag((&a, 1));
    assert_eq!(d1.shape(), &[1]);
    assert_eq!(d1.into_shape(-1).into_vec(), vec![big("2")]);

    // concatenate along axis 0 and axis 1 (same migrated path)
    let b = rt::asarray((vec![big("5"), big("6")], [1, 2], &device));
    let c0 = rt::concatenate((vec![a.clone(), b], 0isize));
    assert_eq!(c0.shape(), &[3, 2]);
    assert_eq!(
        c0.into_shape(-1).into_vec(),
        vec![big("10000000000000000000000000"), big("2"), big("3"), big("4"), big("5"), big("6"),]
    );
    let b2 = rt::asarray((vec![big("7"), big("8")], [2, 1], &device));
    let c1 = rt::concatenate((vec![a, b2], 1isize));
    assert_eq!(c1.shape(), &[2, 3]);
    assert_eq!(
        c1.into_shape(-1).into_vec(),
        vec![big("10000000000000000000000000"), big("2"), big("7"), big("3"), big("4"), big("8"),]
    );
}

static GUARD_CREATED: AtomicUsize = AtomicUsize::new(0);
static GUARD_DROPPED: AtomicUsize = AtomicUsize::new(0);

/// `Default`-constructible non-POD guard (`diag`/`concatenate` require
/// `T: Default`); counts constructions (including clones) and drops via
/// statics. The pre-migration code (`empty` + `assign`) dropped
/// uninitialized memory interpreted as this type on every call.
struct CtorGuard {
    _payload: Vec<u8>,
}

impl CtorGuard {
    fn create() -> Self {
        GUARD_CREATED.fetch_add(1, Ordering::SeqCst);
        CtorGuard { _payload: vec![0x5A; 64] }
    }
}

impl Clone for CtorGuard {
    fn clone(&self) -> Self {
        Self::create()
    }
}

impl Default for CtorGuard {
    fn default() -> Self {
        Self::create()
    }
}

impl Drop for CtorGuard {
    fn drop(&mut self) {
        GUARD_DROPPED.fetch_add(1, Ordering::SeqCst);
    }
}

#[test]
fn test_diag_concat_drop_guard() {
    let mut device = DeviceCpuSerial::default();
    device.set_default_order(RowMajor);
    GUARD_CREATED.store(0, Ordering::SeqCst);
    GUARD_DROPPED.store(0, Ordering::SeqCst);
    {
        let a = rt::asarray((
            vec![CtorGuard::create(), CtorGuard::create(), CtorGuard::create(), CtorGuard::create()],
            [2, 2],
            &device,
        ));
        let _d = rt::diag((&a, 0));
        let b = rt::asarray((vec![CtorGuard::create(), CtorGuard::create()], [1, 2], &device));
        let _c = rt::concatenate((vec![a, b], 0));
        // all results (and every element inside them) drop here
    }
    let created = GUARD_CREATED.load(Ordering::SeqCst);
    let dropped = GUARD_DROPPED.load(Ordering::SeqCst);
    assert!(created > 6, "diag/concat must have cloned elements (created = {created})");
    assert_eq!(created, dropped, "every CtorGuard dropped exactly once (no drop of uninitialized memory)");
}

/* #endregion */
