// Most or all contents generated by AI (agent session 2026-10-05).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_astype {
    use super::*;
    static FUNC: &str = "doc_astype";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);

        // cast to float64
        let b = a.astype::<f64>();
        println!("{b}");
        // [[ 1 2]
        //  [ 3 4]]
        assert_eq!(format!("{b}"), "[[ 1 2]\n [ 3 4]]");
        assert_eq!(b.raw(), &vec![1.0f64, 2.0, 3.0, 4.0]);

        // the same dtype reuses the buffer (a view, no copy)
        let c = a.astype::<i32>();
        assert_eq!(c.raw().as_ptr() as usize, a.raw().as_ptr() as usize);

        // a float tensor cast to an integer dtype truncates
        let e = rt::tensor_from_nested!([[1.5, 2.5], [3.5, 4.5]], &device);
        let d = e.astype::<i32>();
        println!("{d}");
        // [[ 1 2]
        //  [ 3 4]]
        assert_eq!(format!("{d}"), "[[ 1 2]\n [ 3 4]]");
    }
}
