// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_full {
    use super::*;
    static FUNC: &str = "numpy_full";

    #[test]
    fn test_numeric() {
        // NumPy v2.5.2, _core/tests/test_numeric.py, TestCreationFuncs::test_full (line 3393)
        // NumPy's check_function(np.full, 0/1) iterates dtype/order; rstsr checks fill value.
        crate::specify_test!("test_numeric");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.full((2, 2), 7) -> all 7
        let f: Tensor<i32, _> = rt::full(([2, 2], 7, &device));
        assert_eq!(f.shape(), &[2, 2]);
        assert_equal(&f, rt::tensor_from_nested!([[7, 7], [7, 7]], &device), None);

        // np.full((3,), 0) and np.full((3,), 1) (fill_value 0 / 1)
        let f0: Tensor<i32, _> = rt::full(([3], 0, &device));
        assert_eq!(f0.to_vec(), vec![0, 0, 0]);
        let f1: Tensor<i32, _> = rt::full(([3], 1, &device));
        assert_eq!(f1.to_vec(), vec![1, 1, 1]);
    }
}

#[cfg(test)]
mod custom_full {
    use super::*;
    static FUNC: &str = "custom_full";

    #[test]
    fn test_full_like() {
        crate::specify_test!("test_full_like");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((6, &device)).into_shape([2, 3]);
        let f: Tensor<i32, _> = a.full_like(9);
        assert_eq!(f.shape(), &[2, 3]);
        assert_equal(&f, rt::tensor_from_nested!([[9, 9, 9], [9, 9, 9]], &device), None);
    }
}
