// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_linspace {
    use super::*;
    static FUNC: &str = "numpy_linspace";

    #[test]
    fn test_basic() {
        // NumPy v2.5.2, _core/tests/test_function_base.py, TestLinspace::test_basic (line 322)
        // rstsr requires an explicit `num` (NumPy defaults to 50).
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // y = linspace(0, 10); assert_(len(y) == 50)
        let y = rt::linspace((0.0, 10.0, 50, &device));
        assert_eq!(y.shape()[0], 50);

        // y = linspace(2, 10, num=100); assert_(y[-1] == 10)
        let y2: Tensor<f64, _> = rt::linspace((2.0, 10.0, 100, &device));
        let last2: f64 = y2.to_vec()[99];
        assert!((last2 - 10.0).abs() < 1e-9, "last element {last2} != 10");

        // y = linspace(2, 10, endpoint=False); assert_(y[-1] < 10)
        let y3: Tensor<f64, _> = rt::linspace((2.0, 10.0, 100, false, &device));
        let last3: f64 = y3.to_vec()[99];
        assert!(last3 < 10.0, "endpoint=False last element {last3} >= 10");

        // assert_raises(ValueError, linspace, 0, 10, num=-1)
        // N/A: rstsr `num` is usize, so num=-1 is a compile-time type error, not a
        // runtime ValueError.
    }

    #[test]
    fn test_corner() {
        // NumPy v2.5.2, _core/tests/test_function_base.py, TestLinspace::test_corner (line 331)
        crate::specify_test!("test_corner");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // y = list(linspace(0, 1, 1)); assert_(y == [0.0])
        let y = rt::linspace((0.0, 1.0, 1, &device));
        assert_eq!(y.to_vec(), vec![0.0]);
    }
}

#[cfg(test)]
mod custom_linspace {
    use super::*;
    static FUNC: &str = "custom_linspace";

    #[test]
    fn test_values() {
        crate::specify_test!("test_values");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // linspace(0, 1, 5) == [0.0, 0.25, 0.5, 0.75, 1.0]
        let y = rt::linspace((0.0, 1.0, 5, &device));
        let expected = rt::tensor_from_nested!([0.0, 0.25, 0.5, 0.75, 1.0], &device);
        assert_equal(&y, &expected, None);
    }
}
