// Most or all contents generated by AI (agent session 2026-10-05).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod custom_astype {
    use super::*;
    static FUNC: &str = "custom_astype";

    #[test]
    fn test_astype_same_dtype_reuses_buffer() {
        crate::specify_test!("test_astype_same_dtype_reuses_buffer");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let ptr_a = a.raw().as_ptr() as usize;

        // same dtype -> zero-copy view of the same buffer
        let b: TensorCow<i32, _, _> = rt::astype(&a);
        assert_eq!(b.raw().as_ptr() as usize, ptr_a);
        assert_equal(&b, &a, None);

        // consuming form moves the storage (still the same buffer, compact input)
        let c = a.into_astype::<i32>();
        assert_eq!(c.raw().as_ptr() as usize, ptr_a);
        assert_eq!(c.raw(), &vec![1, 2, 3, 4]);
    }

    #[test]
    fn test_astype_cast_dtype() {
        crate::specify_test!("test_astype_cast_dtype");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.arange(6).reshape(2, 3).astype(np.float64)
        let a: Tensor<i32, _> = rt::arange((6, &device)).into_shape([2, 3]);
        let b: TensorCow<f64, _, _> = rt::astype(&a);
        assert_eq!(b.shape(), &[2, 3]);
        assert_eq!(b.raw(), &vec![0.0f64, 1.0, 2.0, 3.0, 4.0, 5.0]);

        // floating dtype change: np.arange(6).astype(np.float32)
        let c: Tensor<f64, _> = a.clone().into_astype::<f64>();
        let d: TensorCow<f32, _, _> = rt::astype(&c);
        assert_eq!(d.raw(), &vec![0.0f32, 1.0, 2.0, 3.0, 4.0, 5.0]);

        // bool -> integer: np.array([True, False]).astype(np.int32)
        let e: Tensor<bool, _> = rt::tensor_from_nested!([true, false, true], &device);
        let f: TensorCow<i32, _, _> = rt::astype(&e);
        assert_eq!(f.raw(), &vec![1i32, 0, 1]);
    }

    #[test]
    fn test_astype_strided_input() {
        crate::specify_test!("test_astype_strided_input");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a strided (non-contiguous) input is materialized contiguously
        // a = np.arange(12).reshape(3, 4)[:, 1::2].astype(np.float64)
        // -> [[1., 3.], [5., 7.], [9., 11.]]
        let a: Tensor<i32, _> = rt::arange((12, &device)).into_shape([3, 4]);
        let v = a.i((.., slice!(1, None, 2)));
        assert!(!v.c_contig());
        let b: TensorCow<f64, _, _> = rt::astype(&v);
        assert_eq!(b.shape(), &[3, 2]);
        assert!(b.c_contig());
        assert_equal(&b, &rt::tensor_from_nested!([[1.0, 3.0], [5.0, 7.0], [9.0, 11.0]], &device), None);
    }

    #[test]
    fn test_astype_fallible_and_method() {
        crate::specify_test!("test_astype_fallible_and_method");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<i32, _> = rt::tensor_from_nested!([1, 2, 3], &device);

        // method form with explicit target
        let b = a.astype::<i64>();
        assert_eq!(b.raw(), &vec![1i64, 2, 3]);

        // fallible forms
        let b: TensorCow<f64, _, _> = rt::astype_f(&a).unwrap();
        assert_eq!(b.raw(), &vec![1.0f64, 2.0, 3.0]);
        let c = a.into_astype_f::<f64>().unwrap();
        assert_eq!(c.raw(), &vec![1.0f64, 2.0, 3.0]);
    }
}
