// Most or all contents generated by AI (model glm-5.3).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// NumPy TestWhere (numpy/_core/tests/test_multiarray.py) translations.
// Known divergences (see tests/tracking/numpy_differences.md):
// - cond must be a bool tensor; NumPy applies truthiness to any dtype
//   (test_dtype_mix non-bool-mask cases are translated via `ne(mask, 0)`).
// - scalar x/y follow rstsr's strong promotion, not NumPy's NEP 50 weak
//   scalars (test_exotic minimal-dtype-with-NaN-scalar cases not applicable).
// - `np.longdouble` / `np.clongdouble` dtypes have no rstsr counterpart.

#[cfg(test)]
mod numpy_where {
    use super::*;
    use num::complex::Complex;
    static FUNC: &str = "numpy_where";

    /// Shared body of NumPy `test_basic` for one dtype: all-true cond, one
    /// false entry at index 7, scalar-cond, 0-d operand broadcast and
    /// strided views (`::2`, `1::2`, `::3`, `1::3`, `::-2`, `::-3`).
    macro_rules! assert_basic_case {
        ($ty:ty, $zero:expr, $one:expr, $device:expr) => {{
            let device = &$device;
            let c_all: Tensor<bool, _, _> = rt::full(([53], true, device));
            let c_none: Tensor<bool, _, _> = rt::full(([53], false, device));
            let t: Tensor<bool, _, _> = rt::full(([], true, device));
            let f: Tensor<bool, _, _> = rt::full(([], false, device));
            let zero0: Tensor<$ty, _, _> = rt::full(([], $zero, device));
            let one0: Tensor<$ty, _, _> = rt::full(([], $one, device));
            let r: Vec<$ty> = (0..53).map(|i| if i == 7 { $zero } else { $one }).collect();
            let cv: Vec<bool> = (0..53).map(|i| i != 7).collect();
            let c = rt::asarray((cv, device));
            let d: Tensor<$ty, _, _> = rt::full(([53], $one, device));
            let e: Tensor<$ty, _, _> = rt::full(([53], $zero, device));

            // scalar-cond cases (NumPy: np.where(True/False, dt(0), dt(1)))
            assert_eq!(rt::r#where(&t, &zero0, &one0).reshape([1]).to_vec(), vec![$zero]);
            assert_eq!(rt::r#where(&f, &zero0, &one0).reshape([1]).to_vec(), vec![$one]);

            // all-true / all-false cond tensors
            assert_eq!(rt::r#where(&c_all, &zero0, &one0).to_vec(), vec![$zero; 53]);
            assert_eq!(rt::r#where(&c_none, &zero0, &one0).to_vec(), vec![$one; 53]);

            // elementwise with 0-d broadcast operands (NumPy: d, e, e[0], d[0])
            assert_eq!(rt::r#where(&c, &e, &e).to_vec(), vec![$zero; 53]);
            assert_eq!(rt::r#where(&c, &d, &e).to_vec(), r);
            assert_eq!(rt::r#where(&c, &d, &zero0).to_vec(), r);
            assert_eq!(rt::r#where(&c, &zero0, &e).to_vec(), vec![$zero; 53]);

            // strided views
            let expected_fwd = |start: usize, step: usize| -> Vec<$ty> {
                (start..53).step_by(step).map(|i| if i == 7 { $zero } else { $one }).collect()
            };
            let expected_rev = |step: usize| -> Vec<$ty> {
                (0..53).rev().step_by(step).map(|i| if i == 7 { $zero } else { $one }).collect()
            };
            let slc = |start: Option<isize>, step: isize| {
                (
                    c.slice(&[slice!(start, None, step).into()]),
                    d.slice(&[slice!(start, None, step).into()]),
                    e.slice(&[slice!(start, None, step).into()]),
                )
            };
            let (cs, ds, es) = slc(None, 2);
            assert_eq!(rt::r#where(&cs, &ds, &es).to_vec(), expected_fwd(0, 2));
            let (cs, ds, es) = slc(Some(1), 2);
            assert_eq!(rt::r#where(&cs, &ds, &es).to_vec(), expected_fwd(1, 2));
            let (cs, ds, es) = slc(None, 3);
            assert_eq!(rt::r#where(&cs, &ds, &es).to_vec(), expected_fwd(0, 3));
            let (cs, ds, es) = slc(Some(1), 3);
            assert_eq!(rt::r#where(&cs, &ds, &es).to_vec(), expected_fwd(1, 3));
            let (cs, ds, es) = slc(None, -2);
            assert_eq!(rt::r#where(&cs, &ds, &es).to_vec(), expected_rev(2));
            let (cs, ds, es) = slc(None, -3);
            assert_eq!(rt::r#where(&cs, &ds, &es).to_vec(), expected_rev(3));
        }};
    }

    #[test]
    fn test_basic() {
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        assert_basic_case!(bool, false, true, device);
        assert_basic_case!(i16, 0, 1, device);
        assert_basic_case!(i32, 0, 1, device);
        assert_basic_case!(i64, 0, 1, device);
        assert_basic_case!(f64, 0.0, 1.0, device);
        assert_basic_case!(Complex<f64>, Complex::new(0.0, 0.0), Complex::new(1.0, 0.0), device);
    }

    #[test]
    fn test_ndim() {
        crate::specify_test!("test_ndim");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // c = [True, False]; a = zeros((2, 25)); b = ones((2, 25))
        // r = where(c[:, None], a, b): row 0 from a, row 1 from b
        let c = rt::tensor_from_nested!([[true], [false]], &device);
        let a: Tensor<f64, _, _> = rt::full(([2, 25], 0.0, &device));
        let b: Tensor<f64, _, _> = rt::full(([2, 25], 1.0, &device));
        let r = rt::r#where(&c, &a, &b);
        assert_eq!(r.shape(), &[2, 25]);
        assert_eq!(r.slice(0).to_vec(), vec![0.0; 25]);
        assert_eq!(r.slice(1).to_vec(), vec![1.0; 25]);

        // transposed operands (stride-swapped views); NumPy uses the plain
        // 1-D c here, right-aligned against the transposed (25, 2) shapes
        let c1 = rt::tensor_from_nested!([true, false], &device);
        let r = rt::r#where(&c1, &a.t(), &b.t());
        assert_eq!(r.shape(), &[25, 2]);
        assert_eq!(r.slice((.., 0)).to_vec(), vec![0.0; 25]);
        assert_eq!(r.slice((.., 1)).to_vec(), vec![1.0; 25]);
    }

    #[test]
    fn test_dtype_mix() {
        crate::specify_test!("test_dtype_mix");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // c = [F,T,F,F,F,F,T,F,F,F,T,F]
        let c = rt::tensor_from_nested!(
            [false, true, false, false, false, false, true, false, false, false, true, false], &device
        );
        let b = rt::tensor_from_nested!([5., 0., 3., 2., -1., -4., 0., -10., 10., 1., 0., 3.], &device);
        let expected = [5., 1., 3., 2., -1., -4., 1., -10., 10., 1., 1., 3.];

        // scalar a (0-d uint32) + float64 b -> float64
        let a: Tensor<u32, _, _> = rt::full(([], 1, &device));
        let r = rt::r#where(&c, &a, &b);
        assert_eq!(r.to_vec(), expected);

        // f32 a + i64 b -> f64 (cross-category promotion, cond excluded)
        let a_f32: Tensor<f32, _, _> = rt::full(([], 1.0, &device));
        let b_i64 = rt::tensor_from_nested!([5, 0, 3, 2, -1, -4, 0, -10, 10, 1, 0, 3], &device);
        let r = rt::r#where(&c, &a_f32, &b_i64);
        assert_eq!(r.to_vec(), expected);

        // non-bool mask (NumPy truthiness): translated via ne(mask, 0)
        let c_int = rt::tensor_from_nested!([0, 34242324, 0, 0, 0, 0, 34242324, 0, 0, 0, 34242324, 0], &device);
        let c_bool = rt::ne(&c_int, 0);
        let r = rt::r#where(&c_bool, &a_f32, &b_i64);
        assert_eq!(r.to_vec(), expected);

        // inverted mask: nonzero at the False positions
        let c_int_inv = rt::tensor_from_nested!(
            [34242324, 0, 34242324, 34242324, 34242324, 34242324, 0, 34242324, 34242324, 34242324, 0, 34242324],
            &device
        );
        let c_bool_inv = rt::ne(&c_int_inv, 0);
        let r = rt::r#where(&c_bool_inv, &b_i64, &a_f32);
        assert_eq!(r.to_vec(), expected);
    }

    #[test]
    fn test_error() {
        crate::specify_test!("test_error");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // cond len 2 vs (4, 5) / (5, 5) inputs: non-broadcastable
        let c = rt::tensor_from_nested!([true, true], &device);
        let a: Tensor<f64, _, _> = rt::full(([4, 5], 1.0, &device));
        let b: Tensor<f64, _, _> = rt::full(([5, 5], 1.0, &device));
        assert!(rt::where_f(&c, &a, &a).is_err());
        assert!(rt::where_f(&c, &a, &b).is_err());
    }

    #[test]
    fn test_exotic() {
        crate::specify_test!("test_exotic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // zero-sized: (0, 3) cond with scalar y, and three-tensor form
        let m: Tensor<bool, _, _> = rt::full(([0, 3], false, &device));
        let b: Tensor<f64, _, _> = rt::full(([0, 3], 1.0, &device));
        let r = rt::r#where(&m, 0.0, &b);
        assert_eq!(r.shape(), &[0, 3]);
        let r = rt::r#where(&m, &b, &b);
        assert_eq!(r.shape(), &[0, 3]);

        // NumPy parts not translated (documented divergences / N-A):
        // - object-dtype selection (no object dtype in rstsr)
        // - minimal-dtype result with NaN/inf Python scalars (weak scalars)
    }
}

#[cfg(test)]
mod custom_where {
    use super::*;
    static FUNC: &str = "custom_where";

    #[test]
    fn test_scalar_args() {
        crate::specify_test!("test_scalar_args");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let c = rt::tensor_from_nested!([true, false, true, false], &device);

        // scalar y: house-strong promotion f32 tensor + f64 literal -> f64
        let x: Tensor<f32, _, _> = rt::full(([4], 1.0, &device));
        let r = rt::r#where(&c, &x, 0.5);
        assert_eq!(r.shape(), &[4]);
        assert_eq!(r.to_vec(), vec![1.0_f64, 0.5, 1.0, 0.5]);

        // scalar x: integer literal with i32 tensor -> i32
        let y = rt::tensor_from_nested!([10, 20, 30, 40], &device);
        let r = rt::r#where(&c, 2, &y);
        assert_eq!(r.to_vec(), vec![2_i32, 20, 2, 40]);

        // bool x/y tensors
        let x = rt::tensor_from_nested!([true, true, false, false], &device);
        let y = rt::tensor_from_nested!([false, false, true, true], &device);
        let r = rt::r#where(&c, &x, &y);
        assert_eq!(r.to_vec(), vec![true, false, false, true]);
    }

    #[test]
    fn test_method_form() {
        crate::specify_test!("test_method_form");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let c = rt::tensor_from_nested!([true, false], &device);
        let x = rt::tensor_from_nested!([1, 2], &device);
        let y = rt::tensor_from_nested!([10, 20], &device);
        let r = c.view().r#where(&x, &y);
        assert_eq!(r.to_vec(), vec![1, 20]);
    }

    #[test]
    fn test_broadcast() {
        crate::specify_test!("test_broadcast");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // cond (3, 1) broadcasts against x (1, 4) and y (4,)
        let c = rt::tensor_from_nested!([[true], [false], [true]], &device);
        let x = rt::tensor_from_nested!([[1, 2, 3, 4]], &device);
        let y = rt::tensor_from_nested!([-1, -2, -3, -4], &device);
        let r = rt::r#where(&c, &x, &y);
        assert_eq!(r.shape(), &[3, 4]);
        assert_eq!(r.reshape([-1]).to_vec(), vec![1, 2, 3, 4, -1, -2, -3, -4, 1, 2, 3, 4]);
    }
}
