// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// NumPy's add/subtract/multiply/divide/remainder tests (test_umath.py) are heavily
// dtype/casting/out=/FP-edge-case oriented and not cleanly transferable; these are
// `custom_*` value tests exercising elementwise binary arithmetic + broadcasting.

#[cfg(test)]
mod custom_add {
    use super::*;
    static FUNC: &str = "custom_add";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let b = rt::tensor_from_nested!([[10, 20], [30, 40]], &device);
        // np.add(a, b) == [[11, 22], [33, 44]]
        assert_equal(&rt::add(&a, &b), &rt::tensor_from_nested!([[11, 22], [33, 44]], &device), None);
        assert_equal(&(&a + &b), &rt::tensor_from_nested!([[11, 22], [33, 44]], &device), None);
    }

    #[test]
    fn test_broadcast() {
        crate::specify_test!("test_broadcast");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a (2,3) + b (3,) broadcasts the row across both rows.
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let b = rt::tensor_from_nested!([10, 20, 30], &device);
        assert_equal(&rt::add(&a, &b), &rt::tensor_from_nested!([[11, 22, 33], [14, 25, 36]], &device), None);
    }
}

#[cfg(test)]
mod custom_sub {
    use super::*;
    static FUNC: &str = "custom_sub";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[10, 20], [30, 40]], &device);
        let b = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        assert_equal(&rt::sub(&a, &b), &rt::tensor_from_nested!([[9, 18], [27, 36]], &device), None);
        assert_equal(&(&a - &b), &rt::tensor_from_nested!([[9, 18], [27, 36]], &device), None);
    }
}

#[cfg(test)]
mod custom_mul {
    use super::*;
    static FUNC: &str = "custom_mul";

    #[test]
    fn test_elementwise_broadcast() {
        crate::specify_test!("test_elementwise_broadcast");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let b = rt::tensor_from_nested!([10, 100], &device);
        // np.multiply(a, b) broadcasts (2,2)*(2,) -> [[10,200],[30,400]]
        assert_equal(&rt::mul(&a, &b), &rt::tensor_from_nested!([[10, 200], [30, 400]], &device), None);
        assert_equal(&(&a * &b), &rt::tensor_from_nested!([[10, 200], [30, 400]], &device), None);
    }
}

#[cfg(test)]
mod custom_div {
    use super::*;
    static FUNC: &str = "custom_div";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // float division (numpy true_divide semantics); use f64 to avoid integer
        // truncation ambiguity.
        let a = rt::tensor_from_nested!([[10.0, 20.0], [30.0, 40.0]], &device);
        let b = rt::tensor_from_nested!([[2.0, 4.0], [5.0, 8.0]], &device);
        assert_equal(&rt::div(&a, &b), &rt::tensor_from_nested!([[5.0, 5.0], [6.0, 5.0]], &device), None);
        assert_equal(&(&a / &b), &rt::tensor_from_nested!([[5.0, 5.0], [6.0, 5.0]], &device), None);
    }
}

#[cfg(test)]
mod custom_rem {
    use super::*;
    static FUNC: &str = "custom_rem";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.remainder(a, b)
        let a = rt::tensor_from_nested!([[10, 21], [33, 44]], &device);
        let b = rt::tensor_from_nested!([[3, 4], [5, 7]], &device);
        // rt::rem (free function) is correct for 1-D and 2-D.
        assert_equal(&rt::rem(&a, &b), &rt::tensor_from_nested!([[1, 1], [3, 2]], &device), None);
        // BUG: the `%` (Rem) operator returns garbage ([135, 187, 319, 440]) instead of
        // [[1,1],[3,2]], while the `+ - * /` operators and rt::rem are correct.
        // See numpy_differences.md; the operator is therefore not asserted here.
    }
}
