// Most or all contents generated by AI (model glm-5.2).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_indexing {
    use super::*;
    static FUNC: &str = "doc_indexing";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let m = rt::arange((12, &device)).into_shape([3, 4]);
        println!("{}", m.i(1));
        // [ 4 5 6 7]
        println!("{}", m.i((.., slice!(1, 3))));
        // [[ 1 2]
        //  [ 5 6]
        //  [ 9 10]]
        println!("{:?}", m.i((.., None)).shape());
        // [3, 1, 4]
        let v = rt::arange((6, &device));
        println!("{:?}", rt::index_select(&v, 0, [1, 3, 5]));
        // [1, 3, 5]
        crate::test_utils::assert_equal(m.i(1), &rt::tensor_from_nested!([4, 5, 6, 7], &device), None);
        crate::test_utils::assert_equal(
            m.i((.., slice!(1, 3))),
            &rt::tensor_from_nested!([[1, 2], [5, 6], [9, 10]], &device),
            None,
        );
        assert_eq!(m.i((.., None)).shape(), &[3, 1, 4]);
        crate::test_utils::assert_equal(
            rt::index_select(&v, 0, [1, 3, 5]),
            &rt::tensor_from_nested!([1, 3, 5], &device),
            None,
        );
    }
}
