// Most or all contents generated by AI (agent session 2026-10-05).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_sum_with_args {
    use super::*;
    static FUNC: &str = "doc_sum_with_args";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);

        // sum along the second axis, keeping it as a size-1 dimension
        println!("{}", a.sum_with_args((1, true)));
        // [[ 6]
        //  [ 15]]
        assert_eq!(format!("{}", a.sum_with_args((1, true))), "[[ 6]\n [ 15]]");

        // whole-array reduce, keeping all axes
        println!("{}", rt::sum_with_args(&a, true));
        // [[ 21]]
        assert_eq!(format!("{}", rt::sum_with_args(&a, true)), "[[ 21]]");

        // axes without keepdims drop the reduced axis
        println!("{}", rt::sum_with_args(&a, 0));
        // [ 5 7 9]
        assert_eq!(format!("{}", rt::sum_with_args(&a, 0)), "[ 5 7 9]");
        assert_eq!(rt::sum_with_args(&a, 0).to_vec(), vec![5, 7, 9]);
    }
}

mod doc_sum_with_dtype {
    use super::*;
    static FUNC: &str = "doc_sum_with_dtype";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // an int8 tensor accumulated in int64 (no overflow)
        let a: Tensor<i8, _> = rt::tensor_from_nested!([100, 100, 100], &device);
        let s: Tensor<i64, _> = a.sum_with_dtype(());
        println!("{s}");
        // 300
        assert_eq!(format!("{s}"), "300");
        assert_eq!(s.to_scalar(), 300i64);

        // an integer tensor accumulated in float64
        let b: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let m: Tensor<f64, _> = b.mean_with_dtype((0, true));
        println!("{m}");
        // [[ 2 3]]
        assert_eq!(format!("{m}"), "[[ 2 3]]");
        assert_eq!(m.raw(), &[2.0f64, 3.0]);
    }
}

mod doc_var_with_args {
    use super::*;
    static FUNC: &str = "doc_var_with_args";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]], &device);

        // population variance (default correction 0.0)
        println!("{}", a.var_with_args(1));
        // [ 0.6666666666666666 0.6666666666666666]
        assert_eq!(format!("{}", a.var_with_args(1)), "[ 0.6666666666666666 0.6666666666666666]");

        // sample variance: Delta degrees of freedom = 1
        println!("{}", a.var_with_args(VarArgs::default().axes(1).correction(1.0)));
        // [ 1 1]
        assert_eq!(format!("{}", a.var_with_args(VarArgs::default().axes(1).correction(1.0))), "[ 1 1]");
        assert_eq!(a.var_with_args(VarArgs::default().axes(1).correction(1.0)).to_vec(), vec![1.0, 1.0]);
    }
}
