name: rstsr-openblas tests arm64

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        architecture: aarch64
        miniconda-version: "latest"
    - name: install dependencies
      run: sudo apt-get install -y libopenblas-openmp-dev
    - name: conda environment setup
      run: |
        conda init; source $HOME/.bashrc; conda activate
        conda install -y numpy scipy
    - name: manifest initialization
      run: |
        conda init; source $HOME/.bashrc; conda activate
        cd rstsr-test-manifest/resources
        python gen_rand_vec.py
    - name: validate manifest (driver_validation_f64)
      run: |
        conda init; source $HOME/.bashrc; conda activate
        cd crates-device/rstsr-openblas/tests/test_driver_impl
        python driver_validation_f64.py
    - name: validate manifest (func_validation_f64)
      run: |
        conda init; source $HOME/.bashrc; conda activate
        cd crates-device/rstsr-openblas/tests/test_linalg_func
        python func_validation_f64.py
    - name: test
      run: RSTSR_DEV=1 cargo test -p rstsr-openblas --release --features="openmp linalg"
